apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app2
    # matchExpressions: 
    #   - {key: app, operator: NotIn, values: [web-app2, first-app]}
  template:
    metadata:
      labels:
        app: web-app2
    spec:
      containers:
        - name: simple-web-node-app
          image: orifjon9/ec2-docker-simple-web-app:2
          env:
            - name: PORT
              # value: 80
              valueFrom:
                configMapKeyRef:
                  name: simple-web-app-env
                  key: port
            - name: STORAGE
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: simple-web-app-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ..
        #   image: ...
      volumes:
        - name: story-volume
          persistentVolumeClaim: 
            claimName: host-pvc