apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-backend
spec:
  selector:
    app: web-app2
  ports: 
    - protocol: "TCP"
      port: 80
      targetPort: 80 ## make sure app running port is correct
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 433
  type: LoadBalancer